# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20171202_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'MySubscriber', 'verbose_name_plural': 'All Subscribes'},
        ),
    ]
